[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.run]
script = '''
#!@duckscript

exec cargo +nightly build -p rust-winhook-demo-core --release
exec cargo +nightly build -p _dll --release
exec cargo +nightly run -p _injector --release
'''

[tasks.run-x86]
script = '''
#!@duckscript

exec cargo +nightly build -p rust-winhook-demo-core --target i686-pc-windows-msvc --release
exec cargo +nightly build -p _dll --target i686-pc-windows-msvc --release
exec cargo +nightly run -p _injector --target i686-pc-windows-msvc --release
'''
