[package]
name = "_dll"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
_utils = { path = "../utils" }

anyhow = { workspace = true }
once_cell = { workspace = true }
env_logger = { workspace = true }

windows = { workspace = true }
retour = { version = "^0.3", features = ["static-detour"] }
