[package]
name = "_injector"
version.workspace = true
edition.workspace = true

[dependencies]
_utils = { path = "../utils" }

anyhow = { workspace = true }
env_logger = { workspace = true }

dll-syringe = "^0.15"
