[package]
name = "rust-winhook-demo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "^0.52", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
] }
