[package]
name = "_utils"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
once_cell = { workspace = true }

base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
postcard = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = { workspace = true }
tokio = { workspace = true }
interprocess = "^1"
